"""Magnetic field solver for solenoid coils."""

import numpy as np
from scipy.special import ellipk, ellipe
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from data.coils import Solenoid
from data.solutions import MagneticFieldSolution
from utils.constants import MU0


class BFieldSolver:
    """Computes B(r,z) using elliptic integrals for circular loops."""

    def __init__(self, solenoid: Solenoid):
        self.sol = solenoid

    def _turn_filament_grid(self, turn, n_side: int = 9):
        """Return a distributed current model for a turn.

        Each turn is approximated as a set of 81 filaments spread uniformly over
        the actual stack cross-section. This removes the 1/r singularity from a
        single filament model and keeps the field map physically bounded.
        """
        if not hasattr(turn.cable, "stack"):
            return [(turn.r_center, turn.z_center, turn.current)]

        half_radial = 0.5 * turn.cable.stack.width
        half_axial = 0.5 * turn.cable.stack.height
        filaments = []
        filament_current = turn.current / (n_side * n_side)
        radial_step = 2.0 * half_radial / n_side
        axial_step = 2.0 * half_axial / n_side
        for i in range(n_side):
            for j in range(n_side):
                r_f = turn.r_center - half_radial + (i + 0.5) * radial_step
                z_f = turn.z_center - half_axial + (j + 0.5) * axial_step
                filaments.append((r_f, z_f, filament_current))
        return filaments

    def _turn_field(self, turn, R: np.ndarray, Z: np.ndarray, n_side: int = 9):
        """Field generated by one turn using a smeared filament model."""
        Br_tot = np.zeros_like(R, dtype=float)
        Bz_tot = np.zeros_like(R, dtype=float)
        for r_f, z_f, I_f in self._turn_filament_grid(turn, n_side=n_side):
            br, bz = self._loop_field(r_f, z_f, I_f, R, Z)
            Br_tot += br
            Bz_tot += bz
        return Br_tot, Bz_tot

    def compute(
        self,
        r_max: float = None,
        z_max: float = None,
        nr: int = 60,
        nz: int = 80,
        exclude_turn_singularities: bool = True,
        filament_grid_size: int = 9,
    ) -> MagneticFieldSolution:
        """Compute magnetic field solution using a distributed filament model."""
        if r_max is None:
            r_max = self.sol.r_outer * 2.0
        if z_max is None:
            z_max = self.sol.height * 0.75

        r_1d = np.linspace(0, r_max, nr)
        z_1d = np.linspace(-z_max, z_max, nz)
        R, Z = np.meshgrid(r_1d, z_1d, indexing='ij')

        Br_tot = np.zeros((nr, nz), dtype=float)
        Bz_tot = np.zeros((nr, nz), dtype=float)

        for lay in self.sol.layers:
            br, bz = self._turn_field(lay, R, Z, n_side=filament_grid_size)
            Br_tot += br
            Bz_tot += bz

        B_mag = np.sqrt(Br_tot**2 + Bz_tot**2)

        if exclude_turn_singularities:
            # The distributed model removes the exact filament singularity, but
            # we still filter any non-finite values for safety.
            B_mag = np.nan_to_num(B_mag, nan=0.0, posinf=np.finfo(float).max, neginf=-np.finfo(float).max)
            Br_tot = np.nan_to_num(Br_tot, nan=0.0, posinf=np.finfo(float).max, neginf=-np.finfo(float).max)
            Bz_tot = np.nan_to_num(Bz_tot, nan=0.0, posinf=np.finfo(float).max, neginf=-np.finfo(float).max)

        return MagneticFieldSolution(
            r=r_1d,
            z=z_1d,
            Br=Br_tot,
            Bz=Bz_tot,
            Bmag=B_mag
        )

    def _loop_field(self, a: float, z0: float, I: float,
                    R: np.ndarray, Z: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        """Field from single loop."""
        r = np.where(R < 1e-9, 1e-9, R)
        dz = Z - z0
        Q = (a + r)**2 + dz**2
        D = (a - r)**2 + dz**2
        k2 = np.clip(4 * a * r / Q, 0, 1 - 1e-10)
        K = ellipk(k2)
        E = ellipe(k2)
        sqQ = np.sqrt(Q)
        pre = MU0 * I / (2 * np.pi)
        Bz = pre / sqQ * (K + (a**2 - r**2 - dz**2) / D * E)
        Br = pre * dz / (r * sqQ) * (-K + (a**2 + r**2 + dz**2) / D * E)
        Br = np.where(R < 1e-9, 0.0, Br)
        return Br, Bz